// Generated by CoffeeScript 1.4.0
(function() {
  var c, game;

  game = {
    init: function() {
      if (!gfx.init()) {
        alert("Could not set up game canvas!");
        return;
      }
      return gfx.clear();
    }
  };

  game.init();

  c = gfx.ctx;

  c.fillStyle = "orange";

  c.fillRect(10, 10, 300, 80);

  c.strokeStyle = "#3f3f3f";

  c.strokeRect(10, 10, 300, 80);

}).call(this);
