// Generated by CoffeeScript 1.4.0
(function() {
  var c;

  c = gfx.ctx;

  c.fillStyle = "orange";

  c.fillRect(10, 10, 300, 80);

  c.strokeStyle('#3f3f3f');

  c.strokeRect(10, 10, 300, 80);

}).call(this);
